# Generated by Django 5.2.17 on 2026-10-04 13:53

import core.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Parça adı')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Parça kodu')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Kategori')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Stok adedi')),
                ('critical_level', models.PositiveIntegerField(default=5, verbose_name='Kritik seviye')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Birim fiyat')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Tedarikçi')),
                ('shelf_location', models.CharField(blank=True, max_length=50, verbose_name='Raf konumu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stok parçası',
                'verbose_name_plural': 'Stok parçaları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('technician', 'Teknisyen'), ('customer', 'Müşteri')], default='customer', max_length=20, verbose_name='Rol')),
                ('is_temporary_password', models.BooleanField(default=True, help_text='Açıksa kullanıcı şifresini değiştirmeden başka sayfaya erişemez.', verbose_name='Geçici şifre kullanıyor')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Geçerli bir telefon numarası girin (örn. 0532 123 45 67).', regex='^\\+?[0-9\\s\\-()]{10,20}$')], verbose_name='Telefon')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Uzmanlık alanı')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='İşe başlama tarihi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Oluşturulma')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, max_length=150, verbose_name='Kullanıcı adı')),
                ('action', models.CharField(choices=[('login', 'Giriş'), ('login_failed', 'Başarısız giriş'), ('logout', 'Çıkış'), ('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('password_change', 'Şifre değiştirme'), ('credentials_sent', 'Giriş bilgisi e-postası'), ('status_change', 'Durum değişikliği'), ('stock_change', 'Stok değişikliği'), ('leave', 'İzin işlemi'), ('other', 'Diğer')], db_index=True, default='other', max_length=20, verbose_name='İşlem')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='Hedef türü')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='Hedef ID')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İşlem kaydı',
                'verbose_name_plural': 'İşlem kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Takip no')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Müşteri adı soyadı')),
                ('customer_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Geçerli bir telefon numarası girin (örn. 0532 123 45 67).', regex='^\\+?[0-9\\s\\-()]{10,20}$')], verbose_name='Müşteri telefonu')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Müşteri e-postası')),
                ('device_type', models.CharField(choices=[('laptop', 'Dizüstü bilgisayar'), ('desktop', 'Masaüstü bilgisayar'), ('phone', 'Telefon'), ('tablet', 'Tablet'), ('printer', 'Yazıcı'), ('tv', 'Televizyon'), ('console', 'Oyun konsolu'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Cihaz tipi')),
                ('brand', models.CharField(max_length=80, verbose_name='Marka')),
                ('model', models.CharField(max_length=120, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seri no')),
                ('accessories', models.CharField(blank=True, max_length=255, verbose_name='Teslim alınan aksesuarlar')),
                ('issue_description', models.TextField(verbose_name='Arıza açıklaması')),
                ('diagnosis_notes', models.TextField(blank=True, verbose_name='Teknisyen tespit notları')),
                ('status', models.CharField(choices=[('received', 'Teslim alındı'), ('diagnosing', 'İnceleniyor'), ('waiting_approval', 'Müşteri onayı bekliyor'), ('waiting_part', 'Parça bekliyor'), ('repairing', 'Tamirde'), ('testing', 'Test aşamasında'), ('ready', 'Teslime hazır'), ('delivered', 'Teslim edildi'), ('unrepairable', 'Onarılamaz'), ('cancelled', 'İptal edildi')], db_index=True, default='received', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=10, verbose_name='Öncelik')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tahmini ücret')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='İşçilik ücreti')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Parça ücreti')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi')),
                ('warranty_months', models.PositiveSmallIntegerField(default=0, verbose_name='Garanti (ay)')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kabul tarihi')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Tahmini teslim')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'role': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL, verbose_name='Atanan teknisyen')),
            ],
            options={
                'verbose_name': 'Cihaz',
                'verbose_name_plural': 'Cihazlar',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('received', 'Teslim alındı'), ('diagnosing', 'İnceleniyor'), ('waiting_approval', 'Müşteri onayı bekliyor'), ('waiting_part', 'Parça bekliyor'), ('repairing', 'Tamirde'), ('testing', 'Test aşamasında'), ('ready', 'Teslime hazır'), ('delivered', 'Teslim edildi'), ('unrepairable', 'Onarılamaz'), ('cancelled', 'İptal edildi')], max_length=20)),
                ('new_status', models.CharField(choices=[('received', 'Teslim alındı'), ('diagnosing', 'İnceleniyor'), ('waiting_approval', 'Müşteri onayı bekliyor'), ('waiting_part', 'Parça bekliyor'), ('repairing', 'Tamirde'), ('testing', 'Test aşamasında'), ('ready', 'Teslime hazır'), ('delivered', 'Teslim edildi'), ('unrepairable', 'Onarılamaz'), ('cancelled', 'İptal edildi')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.device')),
            ],
            options={
                'verbose_name': 'Durum geçmişi',
                'verbose_name_plural': 'Durum geçmişi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stok girişi'), ('out', 'Stok çıkışı (cihaza kullanıldı)'), ('return', 'İade'), ('adjust', 'Sayım düzeltmesi')], max_length=10, verbose_name='Hareket türü')),
                ('quantity', models.IntegerField(help_text='Düzeltmelerde eksi değer girilebilir.', verbose_name='Adet')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.device')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.stockpart')),
            ],
            options={
                'verbose_name': 'Stok hareketi',
                'verbose_name_plural': 'Stok hareketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevicePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Adet')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Birim fiyat (kullanım anı)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='core.device')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='core.stockpart')),
            ],
            options={
                'verbose_name': 'Cihazda kullanılan parça',
                'verbose_name_plural': 'Cihazda kullanılan parçalar',
            },
        ),
        migrations.CreateModel(
            name='TechnicianLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Yıllık izin'), ('sick', 'Hastalık izni (rapor)'), ('excuse', 'Mazeret izni'), ('unpaid', 'Ücretsiz izin'), ('other', 'Diğer')], default='annual', max_length=10, verbose_name='İzin türü')),
                ('start_date', models.DateField(verbose_name='Başlangıç tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('pending', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal edildi')], db_index=True, default='pending', max_length=10, verbose_name='Durum')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.CharField(blank=True, max_length=255, verbose_name='Yönetici notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL, verbose_name='Teknisyen')),
            ],
            options={
                'verbose_name': 'İzin talebi',
                'verbose_name_plural': 'İzin talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
